# Generated by Django 3.2 on 2021-07-23 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 21, 5, 7, 31168), max_length=40),
        ),
    ]
